version: 0.1

phases:
    pre_build:
        commands:
            - pip install virtualenv
            - virtualenv virtual_alexa
            - source virtual_alexa/bin/activate
            - pip install -r requirements.txt
    build:
        commands:
            - zappa update dev
